Repository YAPP-Github/Pokit-iOS, pull requests merged in 2024-09, with the labels that each got.

#117 fix: 페이지네이션 수정
  Projects/Feature/FeatureContentList/Sources/ContentList/ContentListFeature.swift
  Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
Labels: Bug

#118 fix: 카테고리 추가 후 링크 추가 및 수정화면 반영
  Projects/App/Sources/MainTab/MainTabFeature.swift
  Projects/App/Sources/MainTab/MainTabPath.swift
  Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingFeature.swift
  Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift
Labels: Bug

#115 fix: fcm 분기처리 수정
  Projects/App/Resources/Pokit-info.plist
  Projects/App/Sources/AppDelegate/AppDelegateFeature.swift
  Projects/App/Sources/Intro/IntroFeature.swift
  Projects/App/Sources/MainTab/MainTabFeature.swift
  Projects/App/Sources/MainTab/MainTabPath.swift
  Projects/CoreKit/Sources/Data/Client/UserDefaults/UserDefaultsKey.swift
Labels: Bug

#114 1.0.0에서 발견한 버그 수정
  Projects/App/Sources/Intro/IntroFeature.swift
  Projects/App/Sources/MainTab/MainTabPath.swift
  Projects/CoreKit/Sources/Data/DTO/Auth/WithdrawRequest.swift
  Projects/DSKit/Sources/Components/PokitShareSheet.swift
  Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailFeature.swift
  Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailView.swift
  Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailFeature.swift
  Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailView.swift
  Projects/Feature/FeatureContentList/Sources/ContentList/ContentListFeature.swift
  Projects/Feature/FeatureContentList/Sources/ContentList/ContentListView.swift
  Projects/Feature/FeatureLogin/Sources/Login/LoginFeature.swift
  Projects/Feature/FeatureLogin/Sources/Login/LoginView.swift
  Projects/Feature/FeatureLogin/Sources/LoginRoot/LoginRootFeature.swift
  Projects/Feature/FeatureLogin/Sources/LoginRoot/LoginRootView.swift
  Projects/Feature/FeatureLogin/Sources/SelectField/SelectFieldFeature.swift
  Projects/Feature/FeatureLogin/Sources/SignUpDone/SignUpDoneFeature.swift
  Projects/Feature/FeatureLogin/Sources/SignUpDone/SignUpDoneView.swift
  Projects/Feature/FeatureLoginDemo/Sources/FeatureLoginDemoApp.swift
  Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
  Projects/Feature/FeaturePokit/Sources/PokitRootView.swift
  Projects/Feature/FeatureRemind/Sources/Remind/RemindFeature.swift
  Projects/Feature/FeatureRemind/Sources/Remind/RemindView.swift
  Projects/Feature/FeatureSetting/Sources/Search/PokitSearchFeature.swift
  Projects/Feature/FeatureSetting/Sources/Search/PokitSearchView.swift
  Projects/Feature/FeatureSetting/Sources/Setting/PokitSettingFeature.swift
Labels: Fix, Bug

#123 [1.0.3] - 페이지네이션 버그 수정 및 개선
  .github/workflows/develop.yml
  Projects/App/Sources/MainTab/MainTabPath.swift
  Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailFeature.swift
  Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailView.swift
  Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailFeature.swift
  Projects/Feature/FeatureContentList/Sources/ContentList/ContentListFeature.swift
  Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
  Projects/Feature/FeatureRemind/Sources/Remind/RemindView.swift
  Projects/Feature/FeatureSetting/Sources/Search/PokitSearchFeature.swift
  Projects/Feature/FeatureSetting/Sources/Search/PokitSearchView.swift
  Projects/Feature/FeatureSetting/Sources/Search/Sheet/FilterBottomFeature.swift
  Projects/Util/Sources/Extension/DateFormat.swift
Labels: Fix, Bug

#130 Remind 리펙토링
  Projects/App/Resources/Pokit-info.plist
  Projects/App/Sources/MainTab/MainTabFeatureView.swift
  Projects/App/Sources/MainTab/MainTabPath.swift
  Projects/Feature/FeatureRemind/Sources/Remind/RemindFeature.swift
  Projects/Feature/FeatureRemind/Sources/Remind/RemindView.swift
Labels: Refactor
