Repository YAPP-Github/Pokit-iOS, pull requests merged in 2024-12, with the labels that each got.

#166 feat: 1.0.6 버전 업데이트에 따른 기능 추가 및 수정
  Projects/App/Sources/MainTab/MainTabFeature.swift
  Projects/App/Sources/MainTab/MainTabFeatureView.swift
  Projects/App/Sources/MainTab/MainTabPath.swift
  Projects/CoreKit/Sources/Data/DTO/Category/CategoryEditResponse.swift
  Projects/CoreKit/Sources/Data/DTO/Content/ThumbnailRequest.swift
  Projects/CoreKit/Sources/Data/Network/Content/ContentClient+LiveKey.swift
  Projects/CoreKit/Sources/Data/Network/Content/ContentClient+TestKey.swift
  Projects/CoreKit/Sources/Data/Network/Content/ContentClient.swift
  Projects/CoreKit/Sources/Data/Network/Content/ContentEndpoint.swift
  Projects/DSKit/Sources/Components/PokitIconLInput.swift
  Projects/DSKit/Sources/Components/PokitIconRInput.swift
  Projects/DSKit/Sources/Components/PokitLinkCard.swift
  Projects/DSKit/Sources/Components/PokitLinkPopup.swift
  Projects/DSKit/Sources/Components/PokitListButton.swift
  Projects/DSKit/Sources/Components/PokitPartTextArea.swift
  Projects/DSKit/Sources/Components/PokitSelect.swift
  Projects/DSKit/Sources/Components/PokitTextArea.swift
  Projects/DSKit/Sources/Components/PokitTextInput.swift
  Projects/DSKit/Sources/Foundation/PokitInputStyle.swift
  Projects/DSKit/Sources/Modifiers/PokitInputModifier.swift
  Projects/Domain/Sources/Base/BaseContentDetail.swift
  Projects/Domain/Sources/Base/BaseContentItem.swift
  Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailFeature.swift
  Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailView.swift
  Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingFeature.swift
  Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingView.swift
  Projects/Feature/FeatureCategorySharing/Sources/CategorySharing/CategorySharingFeature.swift
  Projects/Feature/FeatureCategorySharing/Sources/CategorySharing/CategorySharingView.swift
  Projects/Feature/FeatureContentCard/Sources/ContentCard/ContentCardFeature.swift
  Projects/Feature/FeatureContentCard/Sources/ContentCard/ContentCardView.swift
  Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailFeature.swift
  Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailView.swift
  Projects/Feature/FeatureContentList/Sources/ContentList/ContentListFeature.swift
  Projects/Feature/FeatureContentList/Sources/ContentList/ContentListView.swift
  Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift
  Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingView.swift
  Projects/Feature/FeatureLogin/Sources/Intro/IntroView.swift
  Projects/Feature/FeatureLogin/Sources/RegisterNickname/RegisterNicknameView.swift
  Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
  Projects/Feature/FeaturePokit/Sources/PokitRootView.swift
  Projects/Feature/FeatureRemind/Sources/Remind/RemindFeature.swift
  Projects/Feature/FeatureRemind/Sources/Remind/RemindView.swift
  Projects/Feature/FeatureSetting/Sources/Search/PokitSearchFeature.swift
  Projects/Feature/FeatureSetting/Sources/Search/PokitSearchView.swift
  Projects/Feature/FeatureSetting/Sources/Setting/NickNameSetting/NickNameSettingFeature.swift
  Projects/Feature/FeatureSetting/Sources/Setting/NickNameSetting/NickNameSettingView.swift
  Projects/Util/Sources/Constants.swift
  Projects/Util/Sources/Extension/View+Extension.swift
Labels: Feat, Design 🎨, Fix

#168 feat: 1.0.6베타 QA 반영
  Projects/App/ShareExtension/Sources/ShareRootFeature.swift
  Projects/App/Sources/AppDelegate/AppDelegateFeature.swift
  Projects/App/Sources/MainTab/MainTabFeature.swift
  Projects/App/Sources/MainTab/MainTabPath.swift
  Projects/CoreKit/Sources/CoreNetwork/TokenInterceptor.swift
  Projects/CoreKit/Sources/Data/Client/KakaoSDK/Share/KakaoShareClient+LiveKey.swift
  Projects/CoreKit/Sources/Data/Client/SocialLogin/Controller/AppleLoginController.swift
  Projects/DSKit/Sources/Components/PokitBadge.swift
  Projects/DSKit/Sources/Components/PokitCalendar.swift
  Projects/DSKit/Sources/Components/PokitLinkCard.swift
  Projects/DSKit/Sources/Components/PokitLinkPreview.swift
  Projects/DSKit/Sources/Components/PokitList.swift
  Projects/DSKit/Sources/Components/PokitListButton.swift
  Projects/DSKit/Sources/Components/PokitSelect.swift
  Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailFeature.swift
  Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailFeature.swift
  Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailView.swift
  Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift
  Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingView.swift
  Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
  Projects/Feature/FeaturePokit/Sources/PokitRootView.swift
  Projects/Feature/FeatureRemind/Sources/Remind/RemindFeature.swift
  Projects/Feature/FeatureSetting/Sources/Alert/PokitAlertBoxFeature.swift
  Projects/Feature/FeatureSetting/Sources/Search/PokitSearchFeature.swift
Labels: Design 🎨, Fix

#172 [feat] #170 앱 아이콘 수정
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Projects/App/Resources/Pokit-info.plist
Labels: Design 🎨

#174 release 1.0.7
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Projects/App/Resources/Pokit-info.plist
Labels: Release 🚀
