Repository YAPP-Github/Pokit-iOS, pull requests merged in 2024-10, with the labels that each got.

#138 fix: DependencyMacro 도입 후 컴파일 충둘문제 수정
  Projects/CoreKit/Sources/Data/Client/SwiftSoupClient/SwiftSoupClient+TestKey.swift
Labels: Bug

#136 CI/CD 및 코드 사이닝 개선
  .github/workflows/appstore_release.yml
  .github/workflows/build_test.yml
  .github/workflows/hotfix.yml
  .github/workflows/release_update.yml
  .github/workflows/testflight_release.yml
  Makefile
  Projects/App/Project.swift
  Projects/CoreKit/Project.swift
  Projects/DSKit/Project.swift
  Projects/Domain/Project.swift
  Projects/SharedThirdPartyLib/Project.swift
  Projects/Util/Project.swift
  Tuist/ProjectDescriptionHelpers/Settings+Extension.swift
  Tuist/ProjectDescriptionHelpers/Target+Extension.swift
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/release_notes.txt
Labels: Feat, Fix, Setting

#142 refactor: 로그인 플로우 Feature 액션 컨벤션 수정
  Projects/Feature/FeatureLogin/Sources/AgreeToTerms/AgreeToTermsFeature.swift
  Projects/Feature/FeatureLogin/Sources/AgreeToTerms/AgreeToTermsView.swift
  Projects/Feature/FeatureLogin/Sources/Login/LoginFeature.swift
  Projects/Feature/FeatureLogin/Sources/Login/LoginView.swift
  Projects/Feature/FeatureLogin/Sources/RegisterNickname/RegisterNicknameFeature.swift
  Projects/Feature/FeatureLogin/Sources/RegisterNickname/RegisterNicknameView.swift
  Projects/Feature/FeatureLogin/Sources/SelectField/SelectFieldFeature.swift
  Projects/Feature/FeatureLogin/Sources/SignUpDone/SignUpDoneFeature.swift
  Projects/Feature/FeatureLogin/Sources/SignUpDone/SignUpDoneView.swift
Labels: Refactor

#141 refactor: ContentSettingFeature 액션 컨벤션 수정
  Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift
  Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingView.swift
Labels: Refactor

#139 refactor: ContentDetailFeature 액션 컨벤션 수정
  Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailFeature.swift
  Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailView.swift
Labels: Refactor

#147 refactor: PokitFeature 액션 수정
  Projects/App/Sources/MainTab/MainTabFeatureView.swift
  Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
  Projects/Feature/FeaturePokit/Sources/PokitRootView.swift
Labels: Refactor

#148 refactor: CategoryDetailFeature 액션 수정
  Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailFeature.swift
  Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailView.swift
  Projects/Feature/FeatureCategoryDetail/Sources/Sheet/CategoryFilterSheet.swift
Labels: Refactor

#150 refactor: CategorySharingFeature 액션 수정
  Projects/Feature/FeatureCategorySharing/Sources/CategorySharing/CategorySharingFeature.swift
  Projects/Feature/FeatureCategorySharing/Sources/CategorySharing/CategorySharingView.swift
Labels: Refactor

#153 Fix: 인스타그램 등 일부 도메인에서 이미지 조회가 안되는 문제 수정
  Projects/App/ShareExtension/Info.plist
  Projects/DSKit/Sources/Components/PokitLinkCard.swift
  Projects/Feature/FeatureRemind/Sources/Remind/RemindView.swift
Labels: Bug
