Repository YAPP-Github/Pokit-iOS, pull requests merged in 2025-03, with the labels that each got.

#190 feat: [2.0.0] 버전 업데이트에 따른 기능 추가 및 수정(마이페이지)
  Projects/CoreKit/Sources/Data/DTO/Base/BaseProfileImageResponse.swift
  Projects/CoreKit/Sources/Data/DTO/Base/BaseUserResponse.swift
  Projects/CoreKit/Sources/Data/DTO/User/ProfileEditRequest.swift
  Projects/CoreKit/Sources/Data/Network/User/UserClient+LiveKey.swift
  Projects/CoreKit/Sources/Data/Network/User/UserClient+TestKey.swift
  Projects/CoreKit/Sources/Data/Network/User/UserClient.swift
  Projects/CoreKit/Sources/Data/Network/User/UserEndpoint.swift
  Projects/DSKit/Resources/Assets.xcassets/image_profile.imageset/Contents.json
  Projects/DSKit/Resources/Assets.xcassets/image_profile.imageset/image_profile.svg
  Projects/DSKit/Sources/Components/PokitProfileBottomSheet.swift
  Projects/DSKit/Sources/Foundation/PokitImage.swift
  Projects/Domain/Sources/Base/BaseProfile.swift
  Projects/Domain/Sources/Base/BaseUser.swift
  Projects/Domain/Sources/DTO/User/BaseProfileImageResponse+Extensions.swift
  Projects/Domain/Sources/DTO/User/BaseUserResponse+Extension.swift
  Projects/Domain/Sources/NicknameSetting/NicknameSetting.swift
  Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingFeature.swift
  Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingView.swift
  Projects/Feature/FeatureSetting/Sources/Setting/NickNameSetting/NickNameSettingFeature.swift
  Projects/Feature/FeatureSetting/Sources/Setting/NickNameSetting/NickNameSettingView.swift
  Projects/Feature/FeatureSetting/Sources/Setting/PokitSettingFeature.swift
  Projects/Feature/FeatureSetting/Sources/Setting/PokitSettingView.swift
Labels: Feat, Fix, API 🛜

#191 feat: [2.0.0] 버전 업데이트에 따른 기능 추가 및 수정(링크 추천 API)
  Projects/App/Sources/MainTab/MainTabFeature.swift
  Projects/App/Sources/MainTab/MainTabPath.swift
  Projects/CoreKit/Sources/Data/DTO/User/InterestRequest.swift
  Projects/CoreKit/Sources/Data/Network/Content/ContentClient+LiveKey.swift
  Projects/CoreKit/Sources/Data/Network/Content/ContentClient+TestKey.swift
  Projects/CoreKit/Sources/Data/Network/Content/ContentClient.swift
  Projects/CoreKit/Sources/Data/Network/Content/ContentEndpoint.swift
  Projects/CoreKit/Sources/Data/Network/User/UserClient+LiveKey.swift
  Projects/CoreKit/Sources/Data/Network/User/UserClient+TestKey.swift
  Projects/CoreKit/Sources/Data/Network/User/UserClient.swift
  Projects/CoreKit/Sources/Data/Network/User/UserEndpoint.swift
  Projects/DSKit/Sources/Components/PokitCaution.swift
  Projects/DSKit/Sources/Components/PokitLinkPopup.swift
  Projects/Domain/Sources/Base/BaseInterest.swift
  Projects/Domain/Sources/DTO/Base/BaseInterest+Extension.swift
  Projects/Domain/Sources/Recommend/Recommend.swift
  Projects/Feature/FeatureRecommend/Sources/Recommend/RecommendFeature.swift
  Projects/Feature/FeatureRecommend/Sources/Recommend/RecommendKeywordBottomSheet.swift
  Projects/Feature/FeatureRecommend/Sources/Recommend/RecommendView.swift
  Projects/Feature/FeatureRecommendDemo/Sources/FeatureRecommendDemoApp.swift
Labels: Design 🎨, Fix, API 🛜

#192 fix: 2.0.0 qa 런타임 에러 수정
  Projects/Feature/FeatureRecommend/Sources/Recommend/RecommendView.swift
Labels: Bug 🔫
